{{
  config(
    materialized = 'table',
    tags         = ['traceability', 'marts', 'fact']
  )
}}

/*
  fct_ai_tool_calls

  One row per tool invocation or autonomous agent action.
  Covers both explicit tool_invoked events and autonomous agent_action events.

  This is the primary audit table for AI agentic behaviour:
    - What tool or agent ran?
    - What data did it access?
    - Did it violate any boundaries?
    - Was it flagged for security risks?

  Powers:
    - Lightdash "AI Agent Activity" panel
    - Security review of autonomous agent actions
    - Compliance: complete agent audit trail

  Grain: one tool call or agent action event
*/

with tool_events as (

    select *
    from {{ ref('stg_trace_events') }}
    where event_type in (
        'tool_invoked',
        'agent_action',
        'agent_boundary_violation'
    )

)

select
    -- Surrogate key
    trace_id,
    parent_trace_id,

    -- Foreign keys
    tenant_id,
    workspace_id,
    user_id,
    session_id,
    request_id,

    -- Event timing
    event_timestamp           as invoked_at,
    date_trunc('day', event_timestamp) as invoked_date,

    -- Actor context
    event_type,
    actor_type,
    actor_id,

    -- Tool / agent identity
    tool_name,
    agent_name,

    -- ── AI AGENTIC: what it did ────────────────────────────────────────
    ai_action_summary,

    -- ── AI AGENTIC: security and boundary ─────────────────────────────
    boundary_violated,
    is_boundary_violation,
    risk_flags,

    -- SQL generated by the tool/agent (if any)
    sql_text,
    sql_hash,

    -- ── COMPLIANCE: sensitivity ────────────────────────────────────────
    sensitivity_level,
    pii_detected,
    pii_fields,

    -- Datasource context
    datasource_type,
    datasource_name,

    -- Governance
    policy_result,
    is_policy_blocked,

    -- Outcome
    status,
    error_code,
    error_message,

    -- Risk classification for this tool call
    case
        when is_boundary_violation              then 'CRITICAL'
        when is_policy_blocked                  then 'HIGH'
        when sensitivity_level = 'HIGH'         then 'HIGH'
        when pii_detected = true                then 'MEDIUM'
        else 'LOW'
    end                       as tool_call_risk_level,

    etl_run_id

from tool_events
